// flow-typed signature: 06014802edd67bb0d149f58185e48e8b
// flow-typed version: <<STUB>>/@brainhubeu/react-carousel_v^1.19.14/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@brainhubeu/react-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@brainhubeu/react-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@brainhubeu/react-carousel/lib/react-carousel' {
  declare module.exports: any;
}

// Filename aliases
declare module '@brainhubeu/react-carousel/lib/react-carousel.js' {
  declare module.exports: $Exports<'@brainhubeu/react-carousel/lib/react-carousel'>;
}
