// flow-typed signature: 244c58fee0b06803e34f6fb5a22dcc16
// flow-typed version: <<STUB>>/activestorage_v^0.1.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'activestorage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'activestorage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'activestorage/app/assets/javascripts/activestorage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'activestorage/app/assets/javascripts/activestorage.js' {
  declare module.exports: $Exports<'activestorage/app/assets/javascripts/activestorage'>;
}
