// flow-typed signature: ab50b7b55d3ed3f8914648ea4b5753a1
// flow-typed version: <<STUB>>/fileapi_v^2.0.27/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fileapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fileapi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fileapi/dist/FileAPI.html5' {
  declare module.exports: any;
}

declare module 'fileapi/dist/FileAPI.html5.min' {
  declare module.exports: any;
}

declare module 'fileapi/dist/FileAPI' {
  declare module.exports: any;
}

declare module 'fileapi/dist/FileAPI.min' {
  declare module.exports: any;
}

declare module 'fileapi/dist/jquery.fileapi.min' {
  declare module.exports: any;
}

declare module 'fileapi/Gruntfile' {
  declare module.exports: any;
}

declare module 'fileapi/plugins/caman.full.min' {
  declare module.exports: any;
}

declare module 'fileapi/plugins/caman.min' {
  declare module.exports: any;
}

declare module 'fileapi/plugins/FileAPI.exif' {
  declare module.exports: any;
}

declare module 'fileapi/plugins/FileAPI.id3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fileapi/dist/FileAPI.html5.js' {
  declare module.exports: $Exports<'fileapi/dist/FileAPI.html5'>;
}
declare module 'fileapi/dist/FileAPI.html5.min.js' {
  declare module.exports: $Exports<'fileapi/dist/FileAPI.html5.min'>;
}
declare module 'fileapi/dist/FileAPI.js' {
  declare module.exports: $Exports<'fileapi/dist/FileAPI'>;
}
declare module 'fileapi/dist/FileAPI.min.js' {
  declare module.exports: $Exports<'fileapi/dist/FileAPI.min'>;
}
declare module 'fileapi/dist/jquery.fileapi.min.js' {
  declare module.exports: $Exports<'fileapi/dist/jquery.fileapi.min'>;
}
declare module 'fileapi/Gruntfile.js' {
  declare module.exports: $Exports<'fileapi/Gruntfile'>;
}
declare module 'fileapi/plugins/caman.full.min.js' {
  declare module.exports: $Exports<'fileapi/plugins/caman.full.min'>;
}
declare module 'fileapi/plugins/caman.min.js' {
  declare module.exports: $Exports<'fileapi/plugins/caman.min'>;
}
declare module 'fileapi/plugins/FileAPI.exif.js' {
  declare module.exports: $Exports<'fileapi/plugins/FileAPI.exif'>;
}
declare module 'fileapi/plugins/FileAPI.id3.js' {
  declare module.exports: $Exports<'fileapi/plugins/FileAPI.id3'>;
}
