// flow-typed signature: f778d3e5b2a2a8ea1ddb0de98fa070f7
// flow-typed version: <<STUB>>/has-flag_v^2.0.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'has-flag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'has-flag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'has-flag/index' {
  declare module.exports: $Exports<'has-flag'>;
}
declare module 'has-flag/index.js' {
  declare module.exports: $Exports<'has-flag'>;
}
