// flow-typed signature: eca5f0498a105445ebc9f9571dc80702
// flow-typed version: <<STUB>>/jsoneditor_v^9.1.4/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsoneditor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsoneditor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsoneditor/dist/jsoneditor-minimalist' {
  declare module.exports: any;
}

declare module 'jsoneditor/dist/jsoneditor-minimalist.min' {
  declare module.exports: any;
}

declare module 'jsoneditor/dist/jsoneditor' {
  declare module.exports: any;
}

declare module 'jsoneditor/dist/jsoneditor.min' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_advanced_demo/src/App' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_advanced_demo/src/App.test' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_advanced_demo/src' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_advanced_demo/src/JSONEditorReact' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_demo/src/App' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_demo/src/App.test' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_demo/src' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/react_demo/src/JSONEditorDemo' {
  declare module.exports: any;
}

declare module 'jsoneditor/examples/requirejs_demo/scripts/main' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ace' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ace/theme-jsoneditor' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/appendNodeFactory' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/assets/jsonlint/jsonlint' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/assets/selectr/selectr' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/autocomplete' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/constants' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ContextMenu' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/createAbsoluteAnchor' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ErrorTable' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/FocusTracker' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/header' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/Highlighter' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/History' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/i18n' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/jmespathQuery' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/JSONEditor' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/jsonUtils' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/ModeSwitcher' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/Node' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/NodeHistory' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/polyfills' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/previewmode' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/SearchBox' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/showMoreNodeFactory' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/showSortModal' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/showTransformModal' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/textmode' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/treemode' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/TreePath' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/tryRequireAjv' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/tryRequireThemeJsonEditor' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/types' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/util' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/validationUtils' {
  declare module.exports: any;
}

declare module 'jsoneditor/src/js/vanilla-picker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsoneditor/dist/jsoneditor-minimalist.js' {
  declare module.exports: $Exports<'jsoneditor/dist/jsoneditor-minimalist'>;
}
declare module 'jsoneditor/dist/jsoneditor-minimalist.min.js' {
  declare module.exports: $Exports<'jsoneditor/dist/jsoneditor-minimalist.min'>;
}
declare module 'jsoneditor/dist/jsoneditor.js' {
  declare module.exports: $Exports<'jsoneditor/dist/jsoneditor'>;
}
declare module 'jsoneditor/dist/jsoneditor.min.js' {
  declare module.exports: $Exports<'jsoneditor/dist/jsoneditor.min'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/App.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src/App'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/App.test.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src/App.test'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/index' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/index.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src'>;
}
declare module 'jsoneditor/examples/react_advanced_demo/src/JSONEditorReact.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_advanced_demo/src/JSONEditorReact'>;
}
declare module 'jsoneditor/examples/react_demo/src/App.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src/App'>;
}
declare module 'jsoneditor/examples/react_demo/src/App.test.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src/App.test'>;
}
declare module 'jsoneditor/examples/react_demo/src/index' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src'>;
}
declare module 'jsoneditor/examples/react_demo/src/index.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src'>;
}
declare module 'jsoneditor/examples/react_demo/src/JSONEditorDemo.js' {
  declare module.exports: $Exports<'jsoneditor/examples/react_demo/src/JSONEditorDemo'>;
}
declare module 'jsoneditor/examples/requirejs_demo/scripts/main.js' {
  declare module.exports: $Exports<'jsoneditor/examples/requirejs_demo/scripts/main'>;
}
declare module 'jsoneditor/index' {
  declare module.exports: $Exports<'jsoneditor'>;
}
declare module 'jsoneditor/index.js' {
  declare module.exports: $Exports<'jsoneditor'>;
}
declare module 'jsoneditor/src/js/ace/index' {
  declare module.exports: $Exports<'jsoneditor/src/js/ace'>;
}
declare module 'jsoneditor/src/js/ace/index.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ace'>;
}
declare module 'jsoneditor/src/js/ace/theme-jsoneditor.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ace/theme-jsoneditor'>;
}
declare module 'jsoneditor/src/js/appendNodeFactory.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/appendNodeFactory'>;
}
declare module 'jsoneditor/src/js/assets/jsonlint/jsonlint.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/assets/jsonlint/jsonlint'>;
}
declare module 'jsoneditor/src/js/assets/selectr/selectr.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/assets/selectr/selectr'>;
}
declare module 'jsoneditor/src/js/autocomplete.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/autocomplete'>;
}
declare module 'jsoneditor/src/js/constants.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/constants'>;
}
declare module 'jsoneditor/src/js/ContextMenu.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ContextMenu'>;
}
declare module 'jsoneditor/src/js/createAbsoluteAnchor.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/createAbsoluteAnchor'>;
}
declare module 'jsoneditor/src/js/ErrorTable.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ErrorTable'>;
}
declare module 'jsoneditor/src/js/FocusTracker.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/FocusTracker'>;
}
declare module 'jsoneditor/src/js/header.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/header'>;
}
declare module 'jsoneditor/src/js/Highlighter.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/Highlighter'>;
}
declare module 'jsoneditor/src/js/History.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/History'>;
}
declare module 'jsoneditor/src/js/i18n.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/i18n'>;
}
declare module 'jsoneditor/src/js/jmespathQuery.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/jmespathQuery'>;
}
declare module 'jsoneditor/src/js/JSONEditor.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/JSONEditor'>;
}
declare module 'jsoneditor/src/js/jsonUtils.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/jsonUtils'>;
}
declare module 'jsoneditor/src/js/ModeSwitcher.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/ModeSwitcher'>;
}
declare module 'jsoneditor/src/js/Node.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/Node'>;
}
declare module 'jsoneditor/src/js/NodeHistory.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/NodeHistory'>;
}
declare module 'jsoneditor/src/js/polyfills.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/polyfills'>;
}
declare module 'jsoneditor/src/js/previewmode.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/previewmode'>;
}
declare module 'jsoneditor/src/js/SearchBox.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/SearchBox'>;
}
declare module 'jsoneditor/src/js/showMoreNodeFactory.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/showMoreNodeFactory'>;
}
declare module 'jsoneditor/src/js/showSortModal.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/showSortModal'>;
}
declare module 'jsoneditor/src/js/showTransformModal.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/showTransformModal'>;
}
declare module 'jsoneditor/src/js/textmode.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/textmode'>;
}
declare module 'jsoneditor/src/js/treemode.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/treemode'>;
}
declare module 'jsoneditor/src/js/TreePath.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/TreePath'>;
}
declare module 'jsoneditor/src/js/tryRequireAjv.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/tryRequireAjv'>;
}
declare module 'jsoneditor/src/js/tryRequireThemeJsonEditor.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/tryRequireThemeJsonEditor'>;
}
declare module 'jsoneditor/src/js/types.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/types'>;
}
declare module 'jsoneditor/src/js/util.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/util'>;
}
declare module 'jsoneditor/src/js/validationUtils.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/validationUtils'>;
}
declare module 'jsoneditor/src/js/vanilla-picker/index' {
  declare module.exports: $Exports<'jsoneditor/src/js/vanilla-picker'>;
}
declare module 'jsoneditor/src/js/vanilla-picker/index.js' {
  declare module.exports: $Exports<'jsoneditor/src/js/vanilla-picker'>;
}
