// flow-typed signature: 4028ef9312513fd4f692e4eaadd6d9d7
// flow-typed version: <<STUB>>/key-js_v^0.1.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'key-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'key-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'key-js/key' {
  declare module.exports: any;
}

declare module 'key-js/key.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'key-js/key.js' {
  declare module.exports: $Exports<'key-js/key'>;
}
declare module 'key-js/key.min.js' {
  declare module.exports: $Exports<'key-js/key.min'>;
}
