// flow-typed signature: c96a14a4d57fe9625ae2d1b56a98e630
// flow-typed version: <<STUB>>/local-time_v^2.1.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'local-time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'local-time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'local-time/app/assets/javascripts/local-time' {
  declare module.exports: any;
}

// Filename aliases
declare module 'local-time/app/assets/javascripts/local-time.js' {
  declare module.exports: $Exports<'local-time/app/assets/javascripts/local-time'>;
}
