// flow-typed signature: 9c1d6ba6346ef5d0ef5f51ff39853353
// flow-typed version: <<STUB>>/null-loader_v^4.0.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'null-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'null-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'null-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'null-loader/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'null-loader/dist/cjs.js' {
  declare module.exports: $Exports<'null-loader/dist/cjs'>;
}
declare module 'null-loader/dist/index' {
  declare module.exports: $Exports<'null-loader/dist'>;
}
declare module 'null-loader/dist/index.js' {
  declare module.exports: $Exports<'null-loader/dist'>;
}
