// flow-typed signature: 45731d0bfa3d1c662da9adaa863af86e
// flow-typed version: <<STUB>>/react_ujs_v^2.4.3/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react_ujs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react_ujs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react_ujs/react_ujs/dist/react_ujs' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/events/detect' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/events/native' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/events/pjax' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/events/turbolinks' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/events/turbolinksClassic' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/events/turbolinksClassicDeprecated' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/getConstructor/fromGlobal' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/getConstructor/fromRequireContext' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/src/getConstructor/fromRequireContextWithGlobalFallback' {
  declare module.exports: any;
}

declare module 'react_ujs/react_ujs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react_ujs/react_ujs/dist/react_ujs.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/dist/react_ujs'>;
}
declare module 'react_ujs/react_ujs/index' {
  declare module.exports: $Exports<'react_ujs/react_ujs'>;
}
declare module 'react_ujs/react_ujs/index.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs'>;
}
declare module 'react_ujs/react_ujs/src/events/detect.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/events/detect'>;
}
declare module 'react_ujs/react_ujs/src/events/native.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/events/native'>;
}
declare module 'react_ujs/react_ujs/src/events/pjax.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/events/pjax'>;
}
declare module 'react_ujs/react_ujs/src/events/turbolinks.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/events/turbolinks'>;
}
declare module 'react_ujs/react_ujs/src/events/turbolinksClassic.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/events/turbolinksClassic'>;
}
declare module 'react_ujs/react_ujs/src/events/turbolinksClassicDeprecated.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/events/turbolinksClassicDeprecated'>;
}
declare module 'react_ujs/react_ujs/src/getConstructor/fromGlobal.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/getConstructor/fromGlobal'>;
}
declare module 'react_ujs/react_ujs/src/getConstructor/fromRequireContext.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/getConstructor/fromRequireContext'>;
}
declare module 'react_ujs/react_ujs/src/getConstructor/fromRequireContextWithGlobalFallback.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/src/getConstructor/fromRequireContextWithGlobalFallback'>;
}
declare module 'react_ujs/react_ujs/webpack.config.js' {
  declare module.exports: $Exports<'react_ujs/react_ujs/webpack.config'>;
}
