// flow-typed signature: 190994bf174ac84a8fc19c933397bcf5
// flow-typed version: <<STUB>>/resize-sensor_v^0.0.6/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resize-sensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resize-sensor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resize-sensor/gruntfile' {
  declare module.exports: any;
}

declare module 'resize-sensor/ResizeSensor' {
  declare module.exports: any;
}

declare module 'resize-sensor/ResizeSensor.min' {
  declare module.exports: any;
}

declare module 'resize-sensor/src/ResizeSensor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resize-sensor/gruntfile.js' {
  declare module.exports: $Exports<'resize-sensor/gruntfile'>;
}
declare module 'resize-sensor/ResizeSensor.js' {
  declare module.exports: $Exports<'resize-sensor/ResizeSensor'>;
}
declare module 'resize-sensor/ResizeSensor.min.js' {
  declare module.exports: $Exports<'resize-sensor/ResizeSensor.min'>;
}
declare module 'resize-sensor/src/ResizeSensor.js' {
  declare module.exports: $Exports<'resize-sensor/src/ResizeSensor'>;
}
