// flow-typed signature: 3a8fd358f81774ae47a962a50da530af
// flow-typed version: <<STUB>>/scriptjs_v^2.5.8/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scriptjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scriptjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scriptjs/demos/js/bar' {
  declare module.exports: any;
}

declare module 'scriptjs/demos/js/baz' {
  declare module.exports: any;
}

declare module 'scriptjs/demos/js/foo' {
  declare module.exports: any;
}

declare module 'scriptjs/demos/js/thunk' {
  declare module.exports: any;
}

declare module 'scriptjs/dist/script' {
  declare module.exports: any;
}

declare module 'scriptjs/dist/script.min' {
  declare module.exports: any;
}

declare module 'scriptjs/Makefile' {
  declare module.exports: any;
}

declare module 'scriptjs/src/ender' {
  declare module.exports: any;
}

declare module 'scriptjs/src/header' {
  declare module.exports: any;
}

declare module 'scriptjs/src/script' {
  declare module.exports: any;
}

declare module 'scriptjs/tests/tests' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/double-load' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/head' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/jquery' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/lab2' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/lab2.min' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/mootools' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/order-a' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/order-b' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/order-c' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/patha' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/pathb' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/pathc' {
  declare module.exports: any;
}

declare module 'scriptjs/vendor/yui-utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scriptjs/demos/js/bar.js' {
  declare module.exports: $Exports<'scriptjs/demos/js/bar'>;
}
declare module 'scriptjs/demos/js/baz.js' {
  declare module.exports: $Exports<'scriptjs/demos/js/baz'>;
}
declare module 'scriptjs/demos/js/foo.js' {
  declare module.exports: $Exports<'scriptjs/demos/js/foo'>;
}
declare module 'scriptjs/demos/js/thunk.js' {
  declare module.exports: $Exports<'scriptjs/demos/js/thunk'>;
}
declare module 'scriptjs/dist/script.js' {
  declare module.exports: $Exports<'scriptjs/dist/script'>;
}
declare module 'scriptjs/dist/script.min.js' {
  declare module.exports: $Exports<'scriptjs/dist/script.min'>;
}
declare module 'scriptjs/Makefile.js' {
  declare module.exports: $Exports<'scriptjs/Makefile'>;
}
declare module 'scriptjs/src/ender.js' {
  declare module.exports: $Exports<'scriptjs/src/ender'>;
}
declare module 'scriptjs/src/header.js' {
  declare module.exports: $Exports<'scriptjs/src/header'>;
}
declare module 'scriptjs/src/script.js' {
  declare module.exports: $Exports<'scriptjs/src/script'>;
}
declare module 'scriptjs/tests/tests.js' {
  declare module.exports: $Exports<'scriptjs/tests/tests'>;
}
declare module 'scriptjs/vendor/double-load.js' {
  declare module.exports: $Exports<'scriptjs/vendor/double-load'>;
}
declare module 'scriptjs/vendor/head.js' {
  declare module.exports: $Exports<'scriptjs/vendor/head'>;
}
declare module 'scriptjs/vendor/jquery.js' {
  declare module.exports: $Exports<'scriptjs/vendor/jquery'>;
}
declare module 'scriptjs/vendor/lab2.js' {
  declare module.exports: $Exports<'scriptjs/vendor/lab2'>;
}
declare module 'scriptjs/vendor/lab2.min.js' {
  declare module.exports: $Exports<'scriptjs/vendor/lab2.min'>;
}
declare module 'scriptjs/vendor/mootools.js' {
  declare module.exports: $Exports<'scriptjs/vendor/mootools'>;
}
declare module 'scriptjs/vendor/order-a.js' {
  declare module.exports: $Exports<'scriptjs/vendor/order-a'>;
}
declare module 'scriptjs/vendor/order-b.js' {
  declare module.exports: $Exports<'scriptjs/vendor/order-b'>;
}
declare module 'scriptjs/vendor/order-c.js' {
  declare module.exports: $Exports<'scriptjs/vendor/order-c'>;
}
declare module 'scriptjs/vendor/patha.js' {
  declare module.exports: $Exports<'scriptjs/vendor/patha'>;
}
declare module 'scriptjs/vendor/pathb.js' {
  declare module.exports: $Exports<'scriptjs/vendor/pathb'>;
}
declare module 'scriptjs/vendor/pathc.js' {
  declare module.exports: $Exports<'scriptjs/vendor/pathc'>;
}
declare module 'scriptjs/vendor/yui-utilities.js' {
  declare module.exports: $Exports<'scriptjs/vendor/yui-utilities'>;
}
