// flow-typed signature: d8e9f800baa809ff7943c1517f177979
// flow-typed version: <<STUB>>/stimulus_v2.0.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stimulus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stimulus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stimulus/dist/stimulus.umd' {
  declare module.exports: any;
}

declare module 'stimulus/webpack-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stimulus/dist/stimulus.umd.js' {
  declare module.exports: $Exports<'stimulus/dist/stimulus.umd'>;
}
declare module 'stimulus/index' {
  declare module.exports: $Exports<'stimulus'>;
}
declare module 'stimulus/index.js' {
  declare module.exports: $Exports<'stimulus'>;
}
declare module 'stimulus/webpack-helpers.js' {
  declare module.exports: $Exports<'stimulus/webpack-helpers'>;
}
