// flow-typed signature: 357c97707bbc5f5e686cfa6e439e48d1
// flow-typed version: <<STUB>>/uppy_v^0.30.4/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uppy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uppy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uppy/bundle' {
  declare module.exports: any;
}

declare module 'uppy/dist/uppy' {
  declare module.exports: any;
}

declare module 'uppy/dist/uppy.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uppy/bundle.js' {
  declare module.exports: $Exports<'uppy/bundle'>;
}
declare module 'uppy/dist/uppy.js' {
  declare module.exports: $Exports<'uppy/dist/uppy'>;
}
declare module 'uppy/dist/uppy.min.js' {
  declare module.exports: $Exports<'uppy/dist/uppy.min'>;
}
declare module 'uppy/index' {
  declare module.exports: $Exports<'uppy'>;
}
declare module 'uppy/index.js' {
  declare module.exports: $Exports<'uppy'>;
}
