// flow-typed signature: c19f99b4d03db662220ca6f421e66ab2
// flow-typed version: <<STUB>>/verge_v^1.10.2/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'verge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'verge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'verge/GruntFile' {
  declare module.exports: any;
}

declare module 'verge/src/ender' {
  declare module.exports: any;
}

declare module 'verge/src/verge' {
  declare module.exports: any;
}

declare module 'verge/test' {
  declare module.exports: any;
}

declare module 'verge/test/vendor/ender' {
  declare module.exports: any;
}

declare module 'verge/test/vendor/ender.min' {
  declare module.exports: any;
}

declare module 'verge/verge' {
  declare module.exports: any;
}

declare module 'verge/verge.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'verge/GruntFile.js' {
  declare module.exports: $Exports<'verge/GruntFile'>;
}
declare module 'verge/src/ender.js' {
  declare module.exports: $Exports<'verge/src/ender'>;
}
declare module 'verge/src/verge.js' {
  declare module.exports: $Exports<'verge/src/verge'>;
}
declare module 'verge/test/index' {
  declare module.exports: $Exports<'verge/test'>;
}
declare module 'verge/test/index.js' {
  declare module.exports: $Exports<'verge/test'>;
}
declare module 'verge/test/vendor/ender.js' {
  declare module.exports: $Exports<'verge/test/vendor/ender'>;
}
declare module 'verge/test/vendor/ender.min.js' {
  declare module.exports: $Exports<'verge/test/vendor/ender.min'>;
}
declare module 'verge/verge.js' {
  declare module.exports: $Exports<'verge/verge'>;
}
declare module 'verge/verge.min.js' {
  declare module.exports: $Exports<'verge/verge.min'>;
}
