// flow-typed signature: 4325fc90c76c2b628f2fe1c5dddfee95
// flow-typed version: <<STUB>>/webpack-strip-block_v^0.3.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-strip-block'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-strip-block' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-strip-block/test/fixtures/example-basic-case' {
  declare module.exports: any;
}

declare module 'webpack-strip-block/test/fixtures/example-custom-tags' {
  declare module.exports: any;
}

declare module 'webpack-strip-block/test/fixtures/example-inline' {
  declare module.exports: any;
}

declare module 'webpack-strip-block/test/fixtures/example-no-outer-whitespace' {
  declare module.exports: any;
}

declare module 'webpack-strip-block/test/fixtures/example-regex-chars' {
  declare module.exports: any;
}

declare module 'webpack-strip-block/test/spec' {
  declare module.exports: any;
}

declare module 'webpack-strip-block/test/test-compiler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-strip-block/index' {
  declare module.exports: $Exports<'webpack-strip-block'>;
}
declare module 'webpack-strip-block/index.js' {
  declare module.exports: $Exports<'webpack-strip-block'>;
}
declare module 'webpack-strip-block/test/fixtures/example-basic-case.js' {
  declare module.exports: $Exports<'webpack-strip-block/test/fixtures/example-basic-case'>;
}
declare module 'webpack-strip-block/test/fixtures/example-custom-tags.js' {
  declare module.exports: $Exports<'webpack-strip-block/test/fixtures/example-custom-tags'>;
}
declare module 'webpack-strip-block/test/fixtures/example-inline.js' {
  declare module.exports: $Exports<'webpack-strip-block/test/fixtures/example-inline'>;
}
declare module 'webpack-strip-block/test/fixtures/example-no-outer-whitespace.js' {
  declare module.exports: $Exports<'webpack-strip-block/test/fixtures/example-no-outer-whitespace'>;
}
declare module 'webpack-strip-block/test/fixtures/example-regex-chars.js' {
  declare module.exports: $Exports<'webpack-strip-block/test/fixtures/example-regex-chars'>;
}
declare module 'webpack-strip-block/test/spec.js' {
  declare module.exports: $Exports<'webpack-strip-block/test/spec'>;
}
declare module 'webpack-strip-block/test/test-compiler.js' {
  declare module.exports: $Exports<'webpack-strip-block/test/test-compiler'>;
}
