// flow-typed signature: 42d2a41bd0e1cbe390168029288bcb9c
// flow-typed version: <<STUB>>/@babel/helper-call-delegate_v^7.6.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/helper-call-delegate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/helper-call-delegate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/helper-call-delegate/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/helper-call-delegate/lib/index' {
  declare module.exports: $Exports<'@babel/helper-call-delegate/lib'>;
}
declare module '@babel/helper-call-delegate/lib/index.js' {
  declare module.exports: $Exports<'@babel/helper-call-delegate/lib'>;
}
