// flow-typed signature: 42cf5684effa84d814c86e705d6eb486
// flow-typed version: <<STUB>>/@babel/plugin-transform-parameters_v^7.10.4/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-parameters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-parameters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-parameters/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-parameters/lib/params' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-parameters/lib/rest' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-parameters/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-parameters/lib'>;
}
declare module '@babel/plugin-transform-parameters/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-parameters/lib'>;
}
declare module '@babel/plugin-transform-parameters/lib/params.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-parameters/lib/params'>;
}
declare module '@babel/plugin-transform-parameters/lib/rest.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-parameters/lib/rest'>;
}
