development:
  redis:
    host: "localhost"
    port: 6379
    inherit_socket: true
    namespace: "sapco"

test:
  redis:
    host: "localhost"
    port: 6379
    inherit_socket: true
    namespace: "sapco"

production:
  redis:
    host: "localhost"
    port: 6379
    inherit_socket: true
    namespace: "sapco"
