// flow-typed signature: f464bad39e62715c9d1c3f83694e11c0
// flow-typed version: <<STUB>>/@prettier/plugin-ruby_v^0.20.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@prettier/plugin-ruby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@prettier/plugin-ruby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@prettier/plugin-ruby/src/embed' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/alias' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/args' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/arrays' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/assign' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/blocks' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/calls' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/case' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/commands' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/conditionals' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/constants' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/flow' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/hashes' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/hooks' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/ints' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/lambdas' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/loops' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/massign' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/methods' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/operators' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/params' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/patterns' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/regexp' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/rescue' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/return' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/scopes' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/statements' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/nodes/strings' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/parse' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/prettier' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/print' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/ruby' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/toProc' {
  declare module.exports: any;
}

declare module '@prettier/plugin-ruby/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@prettier/plugin-ruby/src/embed.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/embed'>;
}
declare module '@prettier/plugin-ruby/src/nodes.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes'>;
}
declare module '@prettier/plugin-ruby/src/nodes/alias.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/alias'>;
}
declare module '@prettier/plugin-ruby/src/nodes/args.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/args'>;
}
declare module '@prettier/plugin-ruby/src/nodes/arrays.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/arrays'>;
}
declare module '@prettier/plugin-ruby/src/nodes/assign.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/assign'>;
}
declare module '@prettier/plugin-ruby/src/nodes/blocks.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/blocks'>;
}
declare module '@prettier/plugin-ruby/src/nodes/calls.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/calls'>;
}
declare module '@prettier/plugin-ruby/src/nodes/case.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/case'>;
}
declare module '@prettier/plugin-ruby/src/nodes/commands.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/commands'>;
}
declare module '@prettier/plugin-ruby/src/nodes/conditionals.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/conditionals'>;
}
declare module '@prettier/plugin-ruby/src/nodes/constants.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/constants'>;
}
declare module '@prettier/plugin-ruby/src/nodes/flow.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/flow'>;
}
declare module '@prettier/plugin-ruby/src/nodes/hashes.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/hashes'>;
}
declare module '@prettier/plugin-ruby/src/nodes/hooks.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/hooks'>;
}
declare module '@prettier/plugin-ruby/src/nodes/ints.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/ints'>;
}
declare module '@prettier/plugin-ruby/src/nodes/lambdas.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/lambdas'>;
}
declare module '@prettier/plugin-ruby/src/nodes/loops.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/loops'>;
}
declare module '@prettier/plugin-ruby/src/nodes/massign.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/massign'>;
}
declare module '@prettier/plugin-ruby/src/nodes/methods.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/methods'>;
}
declare module '@prettier/plugin-ruby/src/nodes/operators.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/operators'>;
}
declare module '@prettier/plugin-ruby/src/nodes/params.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/params'>;
}
declare module '@prettier/plugin-ruby/src/nodes/patterns.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/patterns'>;
}
declare module '@prettier/plugin-ruby/src/nodes/regexp.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/regexp'>;
}
declare module '@prettier/plugin-ruby/src/nodes/rescue.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/rescue'>;
}
declare module '@prettier/plugin-ruby/src/nodes/return.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/return'>;
}
declare module '@prettier/plugin-ruby/src/nodes/scopes.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/scopes'>;
}
declare module '@prettier/plugin-ruby/src/nodes/statements.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/statements'>;
}
declare module '@prettier/plugin-ruby/src/nodes/strings.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/nodes/strings'>;
}
declare module '@prettier/plugin-ruby/src/parse.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/parse'>;
}
declare module '@prettier/plugin-ruby/src/prettier.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/prettier'>;
}
declare module '@prettier/plugin-ruby/src/print.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/print'>;
}
declare module '@prettier/plugin-ruby/src/ruby.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/ruby'>;
}
declare module '@prettier/plugin-ruby/src/toProc.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/toProc'>;
}
declare module '@prettier/plugin-ruby/src/utils.js' {
  declare module.exports: $Exports<'@prettier/plugin-ruby/src/utils'>;
}
